/:
  controller: Global
  action: default

/404:
  controller: Global
  action: page404

/utilisateur:
  controller: User
  action: default

/ajout-d-un-utilisateur:
  controller: User
  action: add

/afficher-un-utilisateur:
  controller: User
  action: show